# Load IMFile module to monitor log files
module(load="imfile")

# Watch Apache Access Log
input(type="imfile"
      File="/var/log/apache2/access.log"
      Tag="apache-access:"
      Severity="info"
      Facility="local7")

# Forward everything to an external server
*.* @172.100.0.1:514
